Created essential check for entry and logfile before creating an entry

diff --git a/plog b/plog
--- a/plog
+++ b/plog
@@ -882,23 +882,30 @@ esac
 
 # ADD ENTRY TO LOG FILE
 
-# Add entry id
-# Uses grep and awk to search for last entry number. Extracts number from # and sorts the numbers
-last_entry_number=$(grep -o "Entry #[0-9]*" "$logfile" | awk -F '#' '{print $NF}' | sort -n | tail -n 1)
-
-# If there is a last entry number
-if [ -n "$last_entry_number" ]
+# Checks if there is an entry or logfile present
+if [ -n "$entry" ] && [ -n "$logfile" ]
 then
-	# New entry number is last + 1
-	entry_number=$((last_entry_number + 1))
+	# Add entry id
+	# Uses grep and awk to search for last entry number. Extracts number from # and sorts the numbers
+	last_entry_number=$(grep -o "Entry #[0-9]*" "$logfile" | awk -F '#' '{print $NF}' | sort -n | tail -n 1)
+
+	# If there is a last entry number
+	if [ -n "$last_entry_number" ]
+	then
+		# New entry number is last + 1
+		entry_number=$((last_entry_number + 1))
+	else
+		# If there are no last entry number, entry number is 1
+		entry_number=1
+	fi
+
+	# Display the current date using the RFC-3339 format (`YYYY-MM-DD hh:mm:ss TZ`)
+	timestamp=$(date --rfc-3339=s)
+
+	# Redirects the log entry to the log file
+	echo -e "\nEntry #$entry_number\n$timestamp\nAuthor: $author\n\n$entry\n\n~~~~~~" >> "$logfile"
+	echo -e "\nEntry #$entry_number added to ${logfile}"
 else
-	# If there are no last entry number, entry number is 1
-	entry_number=1
+	echo "Error: No logfile or no entry present. No entry added."
+	exit 1
 fi
-
-# Display the current date using the RFC-3339 format (`YYYY-MM-DD hh:mm:ss TZ`)
-timestamp=$(date --rfc-3339=s)
-
-# Redirects the log entry to the log file
-echo -e "\nEntry #$entry_number\n$timestamp\nAuthor: $author\n\n$entry\n\n~~~~~~" >> "$logfile"
-echo -e "\nEntry #$entry_number added to ${logfile}"
